Implement scroll menu in get-tickets command
greeveu/discord-ticketbot pull request #16
Opened 2024-01-18 21:34 UTC by JJJannik

Implement such system to scroll through the ticket pages, if a user opened more than 25 tickets to avoid thrown errors
![grafik](https://github.com/greeveu/discord-ticketbot/assets/99122054/5f78c08e-e2b3-4935-81e2-8a77f2b27c51)

2024-02-10 21:15 UTC, Alex1607 requested changes

2024-02-10 21:15 UTC, Alex1607 commented on src/main/java/eu/greev/dcbot/ticketsystem/interactions/buttons/TicketsBackwards.java
> +        for (int i = (currentPage-2) * 25; i < (currentPage-1) * 25; i++) {
Perhaps create a constant for the 25 as the page size

2024-02-10 21:15 UTC, Alex1607 commented on src/main/java/eu/greev/dcbot/ticketsystem/interactions/buttons/TicketsForward.java
> +                Button.primary("tickets-backwards", Emoji.fromUnicode("◀️")),
I think we can use a constant for the Emojis to not recreate them each time

2024-02-10 21:15 UTC, Alex1607 commented on src/main/java/eu/greev/dcbot/ticketsystem/interactions/commands/GetTickets.java
> +                PAGE_SCROLL_CACHE.removeIf(entity -> System.currentTimeMillis() - entity.getTimeCreated() > TimeUnit.HOURS.toMillis(12));
Instead of System.currentTimeMillis and doing some calculations with it use instand.now() and use the before and after methodes

2024-02-10 21:15 UTC, Alex1607 commented on src/main/java/eu/greev/dcbot/ticketsystem/interactions/commands/GetTickets.java
> +        int maxPage = tickets.size() / 25 + (tickets.size() % 25 == 0 ? 0 : 1);
Same constant for the 25 page size

2024-02-11 15:42 UTC, Alex1607 commented on src/main/java/eu/greev/dcbot/ticketsystem/interactions/commands/GetTickets.java
> +                PAGE_SCROLL_CACHE.removeIf(entity -> Instant.now().toEpochMilli() - entity.getTimeCreated() > TimeUnit.HOURS.toMillis(12));
We can use something like this to make it more readable: `Instant.now().minus(12, Hours).isBefore(Instant.ofEpochSecond/Milli(entity.getTimeCreated()))`

2024-02-13 18:52 UTC, Achsion approved these changes

2024-02-13 19:08 UTC, Alex1607 approved these changes

2024-02-13 19:10 UTC, merged